// <auto-generated />
using System;
using BTLDotNET1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTLDotNET1.Migrations
{
    [DbContext(typeof(QLSBDTContext))]
    partial class QLSBDTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTLDotNET1.Models.BaoHanh", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("IdImei")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_imei");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_bat_dau");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("Ngay_ket_thuc");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<int>("ThoiGianBaoHanh")
                        .HasColumnType("int")
                        .HasColumnName("Thoi_gian_bao_hanh");

                    b.HasKey("Id")
                        .HasName("PK__Bao_hanh__3213E83F301DD7EF");

                    b.HasIndex("IdImei");

                    b.ToTable("Bao_hanh", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.ChiTietDiaChi", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("IdHuyenQuan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_huyen_quan");

                    b.Property<string>("IdTinhTp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_tinh_tp");

                    b.Property<string>("IdXaPhuong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_xa_phuong");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.HasKey("Id")
                        .HasName("PK__Chi_tiet__3213E83F723F5DBC");

                    b.HasIndex("IdHuyenQuan");

                    b.HasIndex("IdTinhTp");

                    b.HasIndex("IdXaPhuong");

                    b.ToTable("Chi_tiet_dia_chi", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.ChiTietSanPham", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<double?>("BoNhoTrong")
                        .HasColumnType("float")
                        .HasColumnName("bo_nho_trong");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gia");

                    b.Property<string>("IdCtspKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_ctsp_khuyen_mai");

                    b.Property<string>("IdMauSac")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_mau_sac");

                    b.Property<string>("IdPhuKien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_phu_kien");

                    b.Property<string>("IdSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_san_pham");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<double?>("Ram")
                        .HasColumnType("float")
                        .HasColumnName("ram");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.HasKey("Id")
                        .HasName("PK__Chi_tiet__3213E83FADEBA4C8");

                    b.HasIndex("IdCtspKhuyenMai");

                    b.HasIndex("IdMauSac");

                    b.HasIndex("IdPhuKien");

                    b.HasIndex("IdSanPham");

                    b.ToTable("Chi_tiet_san_pham", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.CtspKhuyenMai", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<decimal?>("GiaGiam")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gia_giam");

                    b.Property<string>("IdKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_khuyen_mai");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__CTSP_khu__3213E83FA712FB91");

                    b.HasIndex("IdKhuyenMai");

                    b.ToTable("CTSP_khuyen_mai", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.Hang", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<string>("Ten")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("Id")
                        .HasName("PK__Hang__3213E83F65373C7C");

                    b.ToTable("Hang", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDon", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("HinhThucThanhToan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("hinh_thuc_thanh_toan");

                    b.Property<string>("IdKh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_kh");

                    b.Property<string>("IdNv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_nv");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date")
                        .HasColumnName("ngay_tao");

                    b.Property<DateOnly?>("NgayThanhToan")
                        .HasColumnType("date")
                        .HasColumnName("ngay_thanh_toan");

                    b.Property<string>("PhanTramGiamGia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("phan_tram_giam_gia");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<string>("TienKhachDua")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tien_khach_dua");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__Hoa_don__3213E83F6EC3E8FE");

                    b.HasIndex("IdKh");

                    b.HasIndex("IdNv");

                    b.ToTable("Hoa_don", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDonChiTiet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("don_gia");

                    b.Property<string>("IdHoaDon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_hoa_don");

                    b.Property<string>("IdSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_san_pham");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("kich_thuoc");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("MauSac")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mau_sac");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.HasKey("Id")
                        .HasName("PK__Hoa_don___3213E83F9A56894B");

                    b.HasIndex("IdHoaDon");

                    b.HasIndex("IdSanPham");

                    b.ToTable("Hoa_don_chi_tiet", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDonTraHang", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghi_chu");

                    b.Property<string>("IdChiTietHoaDon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_chi_tiet_hoa_don");

                    b.Property<string>("IdKh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_kh");

                    b.Property<string>("IdNv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_nv");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma");

                    b.Property<DateOnly?>("NgayTra")
                        .HasColumnType("date")
                        .HasColumnName("ngay_tra");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<string>("TienHoanTraKhach")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tien_hoan_tra_khach");

                    b.HasKey("Id")
                        .HasName("PK__Hoa_don___3213E83F0D8F9B16");

                    b.HasIndex("IdChiTietHoaDon");

                    b.HasIndex("IdKh");

                    b.HasIndex("IdNv");

                    b.ToTable("Hoa_don_tra_hang", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDonTraHangChiTiet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("GiaBan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gia_ban");

                    b.Property<string>("IdHoaDonTraHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_hoa_don_tra_hang");

                    b.Property<string>("IdSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_san_pham");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("so_luong");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.HasKey("Id")
                        .HasName("PK__Hoa_don___3213E83FC2816FC7");

                    b.HasIndex("IdHoaDonTraHang");

                    b.ToTable("Hoa_don_tra_hang_chi_tiet", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.HuyenQuan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("IdTinhTp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_tinh_tp");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("Id")
                        .HasName("PK__Huyen_qu__3213E83F2F6404DB");

                    b.HasIndex("IdTinhTp");

                    b.ToTable("Huyen_quan", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.Imei", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<string>("IdChiTietHoaDon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_chi_tiet_hoa_don");

                    b.Property<string>("IdChiTietSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_chi_tiet_san_pham");

                    b.Property<string>("Imei1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("imei_1")
                        .IsFixedLength();

                    b.Property<string>("Imei2")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("imei_2")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("IdChiTietHoaDon");

                    b.HasIndex("IdChiTietSanPham");

                    b.ToTable("Imei", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.KhachHang", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("IdDiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_dia_chi");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma_kh");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("Sdt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("sdt");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.HasKey("Id")
                        .HasName("PK__Khach_ha__3213E83FF98762DB");

                    b.HasIndex("IdDiaChi");

                    b.ToTable("Khach_hang", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.KhuyenMai", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<string>("TenLoaiKm")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten_loai_km");

                    b.Property<bool?>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id")
                        .HasName("PK__Khuyen_m__3213E83FE5853BEF");

                    b.ToTable("Khuyen_mai", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.MauSac", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<string>("Ten")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("Id")
                        .HasName("PK__Mau_sac__3213E83F61FA53CB");

                    b.ToTable("Mau_sac", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.NhanVien", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("IdDiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_dia_chi");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma_nv");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<string>("Sdt")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sdt");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("vai_tro");

                    b.HasKey("Id")
                        .HasName("PK__Nhan_vie__3213E83FAD164412");

                    b.HasIndex("IdDiaChi");

                    b.ToTable("Nhan_vien", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.PhuKien", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Ma")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.HasKey("Id")
                        .HasName("PK__Phu_kien__3213E83FCFA8671F");

                    b.ToTable("Phu_kien", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.SanPham", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("IdHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_hang");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<string>("Ten")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("Id")
                        .HasName("PK__San_pham__3213E83F245289FB");

                    b.HasIndex("IdHang");

                    b.ToTable("San_pham", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.TinhTp", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("Id")
                        .HasName("PK__Tinh_tp__3213E83F2E64224E");

                    b.ToTable("Tinh_tp", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.XaPhuong", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CreateDate")
                        .HasColumnType("date")
                        .HasColumnName("create_date");

                    b.Property<string>("IdHuyenQuan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("id_huyen_quan");

                    b.Property<DateOnly?>("LastModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_modified_date");

                    b.Property<bool?>("StatusDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("status_Deleted");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ten");

                    b.HasKey("Id")
                        .HasName("PK__Xa_phuon__3213E83F113F27D4");

                    b.HasIndex("IdHuyenQuan");

                    b.ToTable("Xa_phuong", (string)null);
                });

            modelBuilder.Entity("BTLDotNET1.Models.BaoHanh", b =>
                {
                    b.HasOne("BTLDotNET1.Models.Imei", "IdImeiNavigation")
                        .WithMany("BaoHanhs")
                        .HasForeignKey("IdImei")
                        .HasConstraintName("FK_Bao_hanh_Imei");

                    b.Navigation("IdImeiNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.ChiTietDiaChi", b =>
                {
                    b.HasOne("BTLDotNET1.Models.HuyenQuan", "IdHuyenQuanNavigation")
                        .WithMany("ChiTietDiaChis")
                        .HasForeignKey("IdHuyenQuan")
                        .IsRequired()
                        .HasConstraintName("FK_Chi_tiet_dia_chi_Huyen_quan");

                    b.HasOne("BTLDotNET1.Models.TinhTp", "IdTinhTpNavigation")
                        .WithMany("ChiTietDiaChis")
                        .HasForeignKey("IdTinhTp")
                        .IsRequired()
                        .HasConstraintName("FK_Chi_tiet_dia_chi_Tinh_tp");

                    b.HasOne("BTLDotNET1.Models.XaPhuong", "IdXaPhuongNavigation")
                        .WithMany("ChiTietDiaChis")
                        .HasForeignKey("IdXaPhuong")
                        .IsRequired()
                        .HasConstraintName("FK_Chi_tiet_dia_chi_Xa_phuong");

                    b.Navigation("IdHuyenQuanNavigation");

                    b.Navigation("IdTinhTpNavigation");

                    b.Navigation("IdXaPhuongNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.ChiTietSanPham", b =>
                {
                    b.HasOne("BTLDotNET1.Models.CtspKhuyenMai", "IdCtspKhuyenMaiNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("IdCtspKhuyenMai")
                        .IsRequired()
                        .HasConstraintName("FK_Chi_tiet_san_pham_CTSP_khuyen_mai");

                    b.HasOne("BTLDotNET1.Models.MauSac", "IdMauSacNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("IdMauSac")
                        .IsRequired()
                        .HasConstraintName("FK_Chi_tiet_san_pham_Mau_sac");

                    b.HasOne("BTLDotNET1.Models.PhuKien", "IdPhuKienNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("IdPhuKien")
                        .IsRequired()
                        .HasConstraintName("FK_Chi_tiet_san_pham_Phu_kien");

                    b.HasOne("BTLDotNET1.Models.SanPham", "IdSanPhamNavigation")
                        .WithMany("ChiTietSanPhams")
                        .HasForeignKey("IdSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_Chi_tiet_san_pham_San_pham");

                    b.Navigation("IdCtspKhuyenMaiNavigation");

                    b.Navigation("IdMauSacNavigation");

                    b.Navigation("IdPhuKienNavigation");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.CtspKhuyenMai", b =>
                {
                    b.HasOne("BTLDotNET1.Models.KhuyenMai", "IdKhuyenMaiNavigation")
                        .WithMany("CtspKhuyenMais")
                        .HasForeignKey("IdKhuyenMai")
                        .IsRequired()
                        .HasConstraintName("FK_CTSP_khuyen_mai_Khuyen_mai");

                    b.Navigation("IdKhuyenMaiNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDon", b =>
                {
                    b.HasOne("BTLDotNET1.Models.KhachHang", "IdKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKh")
                        .IsRequired()
                        .HasConstraintName("FK_Hoa_don_Khach_hang");

                    b.HasOne("BTLDotNET1.Models.NhanVien", "IdNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNv")
                        .IsRequired()
                        .HasConstraintName("FK_Hoa_don_Nhan_vien");

                    b.Navigation("IdKhNavigation");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDonChiTiet", b =>
                {
                    b.HasOne("BTLDotNET1.Models.HoaDon", "IdHoaDonNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK_Hoa_don_chi_tiet_Hoa_don");

                    b.HasOne("BTLDotNET1.Models.ChiTietSanPham", "IdSanPhamNavigation")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("IdSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_Hoa_don_chi_tiet_Chi_tiet_san_pham");

                    b.Navigation("IdHoaDonNavigation");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDonTraHang", b =>
                {
                    b.HasOne("BTLDotNET1.Models.HoaDonChiTiet", "IdChiTietHoaDonNavigation")
                        .WithMany("HoaDonTraHangs")
                        .HasForeignKey("IdChiTietHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK_Hoa_don_tra_hang_Hoa_don_chi_tiet");

                    b.HasOne("BTLDotNET1.Models.KhachHang", "IdKhNavigation")
                        .WithMany("HoaDonTraHangs")
                        .HasForeignKey("IdKh")
                        .IsRequired()
                        .HasConstraintName("FK_Hoa_don_tra_hang_Khach_hang");

                    b.HasOne("BTLDotNET1.Models.NhanVien", "IdNvNavigation")
                        .WithMany("HoaDonTraHangs")
                        .HasForeignKey("IdNv")
                        .IsRequired()
                        .HasConstraintName("FK_Hoa_don_tra_hang_Nhan_vien");

                    b.Navigation("IdChiTietHoaDonNavigation");

                    b.Navigation("IdKhNavigation");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDonTraHangChiTiet", b =>
                {
                    b.HasOne("BTLDotNET1.Models.HoaDonTraHang", "IdHoaDonTraHangNavigation")
                        .WithMany("HoaDonTraHangChiTiets")
                        .HasForeignKey("IdHoaDonTraHang")
                        .IsRequired()
                        .HasConstraintName("FK_Hoa_don_tra_hang_chi_tiet_Hoa_don_tra_hang");

                    b.Navigation("IdHoaDonTraHangNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.HuyenQuan", b =>
                {
                    b.HasOne("BTLDotNET1.Models.TinhTp", "IdTinhTpNavigation")
                        .WithMany("HuyenQuans")
                        .HasForeignKey("IdTinhTp")
                        .IsRequired()
                        .HasConstraintName("FK_Huyen_quan_Tinh_tp");

                    b.Navigation("IdTinhTpNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.Imei", b =>
                {
                    b.HasOne("BTLDotNET1.Models.HoaDonChiTiet", "IdChiTietHoaDonNavigation")
                        .WithMany("Imeis")
                        .HasForeignKey("IdChiTietHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK_Imei_Hoa_don_chi_tiet");

                    b.HasOne("BTLDotNET1.Models.ChiTietSanPham", "IdChiTietSanPhamNavigation")
                        .WithMany("Imeis")
                        .HasForeignKey("IdChiTietSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_Imei_Chi_tiet_san_pham");

                    b.Navigation("IdChiTietHoaDonNavigation");

                    b.Navigation("IdChiTietSanPhamNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.KhachHang", b =>
                {
                    b.HasOne("BTLDotNET1.Models.ChiTietDiaChi", "IdDiaChiNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("IdDiaChi")
                        .IsRequired()
                        .HasConstraintName("FK_Khach_hang_Chi_tiet_dia_chi");

                    b.Navigation("IdDiaChiNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.NhanVien", b =>
                {
                    b.HasOne("BTLDotNET1.Models.ChiTietDiaChi", "IdDiaChiNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdDiaChi")
                        .IsRequired()
                        .HasConstraintName("FK_Nhan_vien_Chi_tiet_dia_chi");

                    b.Navigation("IdDiaChiNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.SanPham", b =>
                {
                    b.HasOne("BTLDotNET1.Models.Hang", "IdHangNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdHang")
                        .IsRequired()
                        .HasConstraintName("FK_San_pham_Hang");

                    b.Navigation("IdHangNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.XaPhuong", b =>
                {
                    b.HasOne("BTLDotNET1.Models.HuyenQuan", "IdHuyenQuanNavigation")
                        .WithMany("XaPhuongs")
                        .HasForeignKey("IdHuyenQuan")
                        .IsRequired()
                        .HasConstraintName("FK_Xa_phuong_Huyen_quan");

                    b.Navigation("IdHuyenQuanNavigation");
                });

            modelBuilder.Entity("BTLDotNET1.Models.ChiTietDiaChi", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("BTLDotNET1.Models.ChiTietSanPham", b =>
                {
                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("Imeis");
                });

            modelBuilder.Entity("BTLDotNET1.Models.CtspKhuyenMai", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("BTLDotNET1.Models.Hang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDonChiTiet", b =>
                {
                    b.Navigation("HoaDonTraHangs");

                    b.Navigation("Imeis");
                });

            modelBuilder.Entity("BTLDotNET1.Models.HoaDonTraHang", b =>
                {
                    b.Navigation("HoaDonTraHangChiTiets");
                });

            modelBuilder.Entity("BTLDotNET1.Models.HuyenQuan", b =>
                {
                    b.Navigation("ChiTietDiaChis");

                    b.Navigation("XaPhuongs");
                });

            modelBuilder.Entity("BTLDotNET1.Models.Imei", b =>
                {
                    b.Navigation("BaoHanhs");
                });

            modelBuilder.Entity("BTLDotNET1.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDonTraHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BTLDotNET1.Models.KhuyenMai", b =>
                {
                    b.Navigation("CtspKhuyenMais");
                });

            modelBuilder.Entity("BTLDotNET1.Models.MauSac", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("BTLDotNET1.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDonTraHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("BTLDotNET1.Models.PhuKien", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("BTLDotNET1.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietSanPhams");
                });

            modelBuilder.Entity("BTLDotNET1.Models.TinhTp", b =>
                {
                    b.Navigation("ChiTietDiaChis");

                    b.Navigation("HuyenQuans");
                });

            modelBuilder.Entity("BTLDotNET1.Models.XaPhuong", b =>
                {
                    b.Navigation("ChiTietDiaChis");
                });
#pragma warning restore 612, 618
        }
    }
}
